---
title: C6320 | Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: f07ca6bdc7300a4029caf272c80d752997884d68
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 08/22/2018
ms.locfileid: "42687304"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Bu konuda en son sürümünü şu yolda bulunabilir: [C6320](https://docs.microsoft.com/visualstudio/code-quality/c6320).  
  
Uyarı C6320: özel durum filtresi ifadesi exceptıon_execute_handler değil. Bu, işlenmek üzere düşünülmemiş özel durumları maskeleyebilir  
  
 Bu uyarı, yan etkisi exceptıon_execute_handler sabiti __except bloğunun kullanarak gösterir. Bu durumda, deyiminde \__except bloğu istediğiniz belirli bir işlev içinde işlemek için özel durumlar dahil olmak üzere özel durumu işlemek için her zaman yürütülecek. Özel durum işleme, önce kontrol etmenizi öneririz.  
  
## <a name="example"></a>Örnek  
 Aşağıdaki kod __except engelleyin. Bu uyarıyı oluşturur çünkü her türden özel durumları işlemek deneyin:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Bu uyarıyı düzeltmek için `GetExceptionCode` aşağıdaki kodda gösterildiği gibi işleme önce belirli bir özel durumun denetlemek için:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [try-except Deyimi](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



