---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 83dc34d0386101a0840d1283153e072082f6c517
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/02/2019
ms.locfileid: "53884466"
---
# <a name="c6318"></a>C6318
Uyarı C6318: Ill-tanımlı__try /\__except: exceptıon_contınue_search sabitini veya özel durum filtreleyen ifadede sıfır olarak değerlendirilen başka bir sabiti kullanın. Özel durum işleyici bloğu içindeki kod yürütülmez

 Bu uyarı, bu yapılandırılmış özel durum işleyicisinin korumalı bloğunda bir özel durum oluşursa özel durum nedeniyle işlenmeyecek olduğunu gösterir. sabiti `EXCECPTION_CONTINUE_SEARCH` özel durum filtre ifadesinde kullanılır.

 İşleyici bloğu değil çalıştırıldığı için bu kod özel durum işleyici bloğu olmayan korumalı bloğu eşdeğerdir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı üretir:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)