---
title: C6312 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: c53735af9d16660bbd19055a67468e0a7813a260
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/22/2017
---
# <a name="c6312"></a>C6312
C6312 Uyarı: olası sonsuz döngü: try özel durum filtresi ifadesinde sabit exceptıon_contınue_executıon kullanımını-dışında  
  
 Bu uyarı sabiti kullanımını gösterir `EXCEPTION_CONTINUE_EXECUTION` (veya -1 olarak değerlendirir başka bir sabit) filtre ifadesindeki yapılandırılmış özel durum işleyici. Sabit değer kullanımını `EXCEPTION_CONTINUE_EXECUTION` sonsuz bir döngüye neden olabilir. Örneğin, donanım tarafından bir özel durumu oluştu, özel duruma neden yönerge yeniden başlatılır. Özel duruma neden adresi hala hatalı ise, başka bir özel durum gerçekleşir ve aynı şekilde ele alınabilir. Bu, sonsuz bir döngüye neden olur.  
  
 Açık bir çağrı `RaiseException` doğrudan sonsuz bir döngüye neden olur, ancak korunan bloğunda kodunun yürütülmesini devam edecektir. Bu beklenmeyen olabilir ve sonsuz bir döngüde durumunda neden olabilecek `RaiseException` geçersiz bir işaretçi başvurusunun kaldırılmasının önlemek için kullanıldı.  
  
 Genellikle, `EXCEPTION_CONTINUE_EXECUTION` yalnızca özel duruma neden işaretçi ya da temelindeki bellek düzeltmek için bir fırsat sahip filtre ifadesi olarak adlandırılan bir işlev tarafından döndürülen.  
  
## <a name="example"></a>Örnek  
 Aşağıdaki kod bu uyarı üretir:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Bu uyarıyı çözmek için aşağıdaki kodu kullanın:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```