---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 03552bd5990b2533ad6632bbe86776d21afe32ee
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878144"
---
# <a name="c6312"></a>C6312
Uyarı C6312: Olası sonsuz döngü: try haricinde bir özel durum filtresi ifadesinde EXCEPTION_CONTINUE_EXECUTION sabiti kullanımı

 Bu uyarı, yapılandırılmış bir özel durum işleyicisinin filtre ifadesinde sabit `EXCEPTION_CONTINUE_EXECUTION` (veya-1 ' i değerlendiren başka bir sabit) kullanımını gösterir. Sabit değerin kullanımı sonsuz bir döngüye neden olabilir `EXCEPTION_CONTINUE_EXECUTION`. Örneğin, donanım tarafından bir özel durum ortaya çıktığında, özel duruma neden olan yönerge yeniden başlatılır. Özel duruma neden olan adres hala bozuksa, başka bir özel durum oluşur ve aynı şekilde işlenir. Bu, sonsuz bir döngüye neden olur.

 Açık bir `RaiseException` çağrısı sonsuz döngüye doğrudan neden olmaz, ancak korunan bloktaki kodu yürütmeye devam eder. Bu beklenmeyen bir yol olabilir ve `RaiseException` geçersiz bir işaretçinin başvurusunu kaldırmak için kullanılmışsa sonsuz döngüye neden olabilir.

 Genellikle `EXCEPTION_CONTINUE_EXECUTION` yalnızca filtre ifadesinde çağrılan bir işlev tarafından döndürülmelidir, bu da özel duruma veya temeldeki belleğe neden olan işaretçiyi çözme şansı içerir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı oluşturur:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Bu uyarı düzeltmek için aşağıdaki kodu kullanın:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
