---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: fef29c7f6e341cf4cd31991b24bfc209bd902b15
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781477"
---
# <a name="c6320"></a>C6320
Uyarı C6320: özel durum filtresi ifadesi exceptıon_execute_handler değil. Bu, işlenmek üzere düşünülmemiş özel durumları maskeleyebilir

 Bu uyarı, yan etkisi exceptıon_execute_handler sabiti __except bloğunun kullanarak gösterir. Bu durumda, deyiminde \__except bloğu istediğiniz belirli bir işlev içinde işlemek için özel durumlar dahil olmak üzere özel durumu işlemek için her zaman yürütülecek. Özel durum işleme, önce kontrol etmenizi öneririz.

## <a name="example"></a>Örnek
 Aşağıdaki kod __except engelleyin. Bu uyarıyı oluşturur çünkü her türden özel durumları işlemek deneyin:

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 Bu uyarıyı düzeltmek için `GetExceptionCode` aşağıdaki kodda gösterildiği gibi işleme önce belirli bir özel durumun denetlemek için:

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)