---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: c179a18c49ede3cfc654cd84bc11f93f7d3a6419
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 10/07/2019
ms.locfileid: "72012957"
---
# <a name="c6320"></a>C6320
Uyarı C6320: özel durum filtre ifadesi sabit EXCEPTION_EXECUTE_HANDLER. Bu, işlenmesi amaçlanan özel durumları maskeleyebilir

 Bu uyarı, __except bloğunda EXCEPTION_EXECUTE_HANDLER sabiti kullanmanın yan etkisini gösterir. Bu durumda, belirli bir işlevde işlemek istemediğiniz özel durumlar da dahil olmak üzere, @no__t -0 _Except bloğunun içindeki ifade her zaman özel durumu işleyecek şekilde yürütülür. Özel durumu işlemeye başlamadan önce denetlemeniz önerilir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı oluşturur çünkü __except bloğu tüm türlerin özel durumlarını işlemeye çalışacaktır:

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 Bu uyarıyı düzeltmek için, aşağıdaki kodda gösterildiği gibi işlemeyi yapmadan önce belirli bir özel durumu denetlemek için `GetExceptionCode` kullanın:

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)